### PR TITLE
Dart format support

### PR DESCRIPTION
**Pull request by dalugm**

### CODE REVIEW

**Review by raxod502 — CHANGES_REQUESTED** [review]
Thanks! Mind adding test files to go along with the existing formatters, so that we can be sure your formatter doesn't get broken by any future changes?

Also, the style in `apheleia.el` is to use a single space after sentence-ending periods, so we'd want to keep those as is.

**Comment by dalugm** [comment]
> Mind adding test files to go along with the existing formatters, so that we can be sure your formatter doesn't get broken by any future changes?

Sure, I'll do it later.

> Also, the style in `apheleia.el` is to use a single space after sentence-ending periods, so we'd want to keep those as is.

Sorry, I'll revert it in the next commit.

**Comment by dalugm** [comment]
I have no idea why it shown up this error, maybe it's because I'm using borg to mange my configuration?

make test error

**Comment by elken** [comment]
No idea about your setup, the above also fails on non-x64 machines, the below works on my M1

```bash
ARCH=$(uname -m)
case $(uname -m) in
    "x84_64")
        ARCH="x64"
        ;;
    "i386")
        ARCH="ia32"
        ;;
    "aarch64")
        ARCH="arm64"
esac

mkdir /opt/dart
cd /opt/dart
wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.16.2/sdk/dartsdk-linux-$ARCH-release.zip
unzip ./dart*.zip
rm -rf dart*.zip

echo "export PATH=\"$PATH:/opt/dart/dart-sdk/bin\"" >> /etc/bash.bashrc

```

**Comment by dalugm** [comment]
> No idea about your setup, the above also fails on non-x64 machines, the below works on my M1
> 
> ```shell
> ARCH=$(uname -m)
> case $(uname -m) in
>     "x84_64")
>         ARCH="x64"
>         ;;
>     "i386")
>         ARCH="ia32"
>         ;;
>     "aarch64")
>         ARCH="arm64"
> esac
> 
> mkdir /opt/dart
> cd /opt/dart
> wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.16.2/sdk/dartsdk-linux-$ARCH-release.zip
> unzip ./dart*.zip
> rm -rf dart*.zip
> 
> echo "export PATH=\"$PATH:/opt/dart/dart-sdk/bin\"" >> /etc/bash.bashrc
> ```
> 
> giving
> 
> image

Thx, I haven't considered the different architecture. I have applied you solution and hope it works fine now.

**Comment by raxod502** [comment]
> I have no idea why it shown up this error, maybe it's because I'm using borg to mange my configuration?

Yes, it didn't occur to me that we wouldn't be able to run Git commands with just the repo directory mounted into Docker - because the `.git` directory is just a pointer to elsewhere on your filesystem. We don't have a critical dependency on Git, I was only using it to determine the repo root, so I'll push a fix for that to master.

Will take a look at the rest of the PR next.

**Comment by raxod502** [comment]
Issue with Git worktrees should be resolved now.

**Review by raxod502 — APPROVED** [review]
:sparkles: Thanks! I updated the installation script to streamline things, and this looks good to me.

**Pull request merged**
